from pathlib import Path
import json,html,re
P=Path(__file__).resolve().parents[1]
M=json.loads((P/'sequence-12-mois.json').read_text(encoding='utf-8'))
V=P/'visuels';N='#273554'
for d in ['html','apercus-html','texte']: (P/d).mkdir(exist_ok=True)
def e(s):return html.escape(s)
# Les schémas sont des illustrations éditoriales, jamais des captures de résultats.
base='''<style>*{box-sizing:border-box}body{margin:0;background:#eef1f5;color:#273554;font-family:Arial,sans-serif}.art{width:1040px;height:470px;padding:48px 56px;overflow:hidden}.eyebrow{font-size:18px;letter-spacing:2px;margin-bottom:24px}h2{font-size:40px;letter-spacing:-1px;margin:0 0 30px;line-height:1.15}.cols{display:flex;gap:20px}.card{background:white;border:1px solid #d9e0e8;border-radius:14px;padding:25px;flex:1}b{font-size:28px}p{font-size:23px;line-height:1.4;margin:12px 0 0}.small{font-size:17px;color:#657288}.line{height:16px;border-radius:9px;background:#d6dde8;margin:14px 0}.fill{background:#273554;height:100%;border-radius:9px}.step{background:white;border:1px solid #d9e0e8;padding:23px 18px;border-radius:12px;flex:1;text-align:center}.num{font-size:18px;color:#75839a;margin-bottom:20px}.step b{font-size:23px}.arrow{align-self:center;font-size:24px}.foot{margin-top:24px;font-size:17px;color:#657288}</style>'''
arts={
'comparaison':'''<div class="eyebrow" style="font-size:25px;margin-bottom:12px">MÊME BUDGET · EXEMPLE FICTIF</div><h2 style="margin-bottom:22px">Demandes reçues → projets pertinents</h2><div class="card" style="display:flex;align-items:center;justify-content:space-between;padding:18px 26px;margin-bottom:16px"><span style="font-size:28px">Campagne A</span><span style="font-size:64px;font-weight:bold;letter-spacing:2px">20 <span style="color:#a4afc0">→</span> 4</span></div><div class="card" style="display:flex;align-items:center;justify-content:space-between;padding:18px 26px;border:2px solid #273554"><span style="font-size:28px">Campagne B</span><span style="font-size:64px;font-weight:bold;letter-spacing:2px">8 <span style="color:#a4afc0">→</span> 6</span></div>''',
'parcours':'''<div class="eyebrow">DE LA DÉCOUVERTE AU PREMIER ÉCHANGE</div><h2>Un chemin clair vers votre cabinet.</h2><div class="cols" style="margin-top:42px"><div class="step"><div class="num">01</div><b>Votre annonce</b><p>Un besoin reconnu</p></div><div class="arrow">→</div><div class="step"><div class="num">02</div><b>Le formulaire</b><p>Un projet précisé</p></div><div class="arrow">→</div><div class="step"><div class="num">03</div><b>Votre échange</b><p>Une mission à étudier</p></div></div>''',
'delegation':'''<div class="eyebrow">DÉLÉGUER EN GARDANT LA MAIN</div><h2>Chacun dans son rôle.</h2><div class="cols"><div class="card"><b>Votre cabinet</b><p>Les missions recherchées<br>La relation avec les prospects<br>Le choix des projets</p></div><div class="card" style="background:#273554;color:white"><b>Essort</b><p>Les messages et visuels<br>La diffusion publicitaire<br>Les ajustements</p></div></div><div class="foot">Une plateforme dédiée pour partager la visibilité sur les demandes et leur avancement.</div>''',
'intentions':'''<div class="eyebrow">DEUX MOMENTS POUR ÊTRE DÉCOUVERT</div><h2>Votre futur client n’en est pas<br>toujours au même point.</h2><div class="cols"><div class="card"><b>Google</b><p>Il formule une recherche.</p><p class="small">« Architecte rénovation à Rennes »</p></div><div class="card"><b>Facebook · Instagram</b><p>Il reconnaît son besoin.</p><p class="small">« Notre maison devient trop petite. »</p></div></div>''',
'angles':'''<div class="eyebrow">UNE MISSION · DEUX POINTS DE DÉPART</div><h2>La rénovation de maison.</h2><div class="cols"><div class="card"><div class="small">ANGLE 01</div><p><b>La famille s’agrandit.</b></p><p>Repenser l’espace<br>pour rester chez soi.</p></div><div class="card"><div class="small">ANGLE 02</div><p><b>Un nouveau départ.</b></p><p>Transformer une maison<br>avant d’emménager.</p></div></div><div class="foot">Exemples de messages à adapter au positionnement réel du cabinet.</div>''',
'guide-apercu':'''<div style="display:flex;gap:50px;align-items:center"><div style="width:230px;flex-shrink:0;transform:rotate(-5deg);box-shadow:14px 15px 0 #d7dee8"><img src="guide.jpg" style="display:block;width:230px"></div><div><div class="eyebrow">VOTRE GUIDE ESSORT</div><h2 style="font-size:43px">Des idées.<br>Des priorités.<br>Vos prochains projets.</h2><p>Acquisition &amp; marketing<br>pour les architectes et<br>architectes d’intérieur.</p></div></div>'''
}
arts['ajustement']='''<div class="eyebrow">UNE ANNONCE PLUS PRÉCISE</div><h2>Dire quelle mission vous proposez.</h2><div class="card"><p style="font-size:31px;margin:0">« Repensez votre intérieur »</p></div><p style="margin:8px 0;text-align:center">↓</p><div class="card" style="background:#273554;color:white"><p style="font-size:31px;margin:0">« Vous envisagez la rénovation complète<br>de votre appartement ? »</p></div>'''
for k,art in arts.items(): (V/(k+'.html')).write_text('<!doctype html><meta charset="utf-8">'+base+'<div class="art">'+art+'</div>',encoding='utf-8')
# Une seule action principale cliquable dans chaque email.
images=['guide-apercu','villa','parcours','interieur','interieur','delegation','parcours','plans','villa','delegation','interieur','intentions','plans','echange','parcours','conception','comparaison','parcours','delegation','villa','conception','quartier','plans','parcours','delegation','intentions','conception','interieur','delegation','angles','villa','echange']
alts={'guide-apercu':'Aperçu du guide Essort : acquisition et marketing pour architectes.','villa':'Maison contemporaine avec terrasse et piscine.','interieur':'Intérieur contemporain lumineux, ouvert sur le jardin.','plans':'Plans et documents de conception sur une table de travail.','conception':'Travail de conception autour de plans.','echange':'Une équipe réunie autour de documents de travail.','quartier':'Vue aérienne d’un quartier résidentiel.','parcours':'Votre annonce : un besoin reconnu. Le formulaire : un projet précisé. Votre échange : une mission à étudier.','delegation':'Le cabinet choisit ses missions et échange avec les prospects. Essort prépare, diffuse et ajuste les publicités. Le suivi est partagé.','intentions':'Google répond à une recherche formulée ; Facebook et Instagram peuvent faire reconnaître un besoin avant la recherche.','comparaison':'Exemple fictif, à budget identique : campagne A, 20 demandes dont 4 pertinentes ; campagne B, 8 demandes dont 6 pertinentes.','angles':'Deux exemples d’angles pour la rénovation : adapter une maison à une famille qui s’agrandit ; transformer une maison achetée avant d’emménager.'}
labels={'Guide':'Ouvrir mon guide','Méthode':'Découvrir la méthode Essort','Rendez-vous':'Réserver mon échange'}
shorts={'E10':'Découvrir le suivi avec Essort','E17':'Parlons de vos projets cibles','E23':'Définir mes priorités','E25':'Parlons de mon cabinet','E29':'Définir ce que je délègue','E31':'Préparer la suite ensemble'}
css='''body{margin:0;padding:0;width:100%!important;background:#f4f5f7;-webkit-text-size-adjust:100%;}table{border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt;}img{border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic;}a{color:#273554;}@media only screen and (max-width:620px){.pad{padding-left:24px!important;padding-right:24px!important}.headline{font-size:30px!important;line-height:35px!important}.outer{padding:0!important}.card{border:0!important}.logo{width:135px!important}.kicker{font-size:9px!important;letter-spacing:1px!important}.button{font-size:14px!important}.cta-pad{padding:23px!important}}'''
manifest=[]
for i,x in enumerate(M):
    parts=x['corps'].split('\n\n');last=parts.pop()
    match=re.search(r'\[([^\]]+)\]\((https://[^)]+)\)',last)
    assert match,x['id']
    url=match[2];label=shorts.get(x['id'],labels[x['cta']])
    detail=(last[:match.start()]+last[match.end():]).strip().lstrip('. ').strip()
    titles=[
        'Vos prochains projets commencent ici.', 'Attirons les projets qui vous ressemblent.',
        'Faites découvrir votre cabinet.', 'Donnez toute sa place à votre expertise.',
        'Votre cabinet. Votre manière de vous faire connaître.', 'La conception pour vous. La diffusion pour nous.',
        'Faites place aux bonnes conversations.', 'Choisissons les bonnes priorités.',
        'Donnez une direction à vos demandes.', 'Déléguez avec une vue claire.',
        'Soyez présent dès les premières envies.', 'Trouvons votre premier levier.',
        'Préparons vos prochaines missions.', 'Prenons le temps de parler de votre cabinet.',
        'Regardez ce que les demandes apportent.', 'Votre approche mérite déjà d’être vue.',
        'Visons les projets qui comptent pour vous.', 'Confiez-nous le parcours complet.',
        'Vous fixez le cap. Nous pilotons la diffusion.', 'Faites connaître le cabinet de demain.',
        'Votre travail mérite la bonne audience.', 'Développez votre activité dans votre secteur.',
        'Commençons par ce qui vous sera utile.', 'Attirons les missions que vous recherchez.',
        'Découvrez notre façon de travailler.', 'Faites le lien avec vos futurs clients.',
        'Gardez votre énergie pour concevoir.', 'Faites comprendre ce qui vous distingue.',
        'Choisissez ce que vous nous confiez.', 'Trouvons les mots qui parlent à vos clients.',
        'Donnons une direction à la suite.', 'Passons du guide à votre cabinet.'
    ]
    context={'Guide':'LE GUIDE ESSORT','Méthode':'LA MÉTHODE ESSORT','Rendez-vous':'UN ÉCHANGE AVEC LOYS & ENZO'}[x['cta']]
    action=f'''<table role="presentation" width="100%" bgcolor="#273554" style="background:#273554;border-radius:3px"><tr><td class="cta-pad" style="padding:28px 30px 30px">
<table role="presentation" width="100%"><tr><td style="font:10px/17px Arial,sans-serif;letter-spacing:1.5px;color:#d5deef">{context}</td><td align="right" style="font:30px/30px Georgia,serif;color:#ffffff">✦</td></tr></table>
<p style="margin:19px 0 15px;font:29px/34px Georgia,serif;letter-spacing:-.3px;color:#ffffff">{e(titles[i])}</p>
<p style="margin:0 0 23px;font:14px/23px Arial,sans-serif;color:#e1e6ef">{e(detail) if detail else ('À lire à votre rythme, selon les priorités de votre cabinet.' if x['cta']=='Guide' else 'Découvrez notre fonctionnement et ce que vous pouvez nous déléguer.')}</p>
<!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="{e(url)}" style="height:50px;v-text-anchor:middle;width:270px" arcsize="5%" strokecolor="#ffffff" fillcolor="#ffffff"><w:anchorlock/><center style="color:#273554;font-family:Arial,sans-serif;font-size:15px;font-weight:bold">{e(label)}</center></v:roundrect><![endif]-->
<!--[if !mso]><!--><table role="presentation" width="100%"><tr><td bgcolor="#ffffff" style="border-radius:3px"><a class="button" href="{e(url)}" target="_blank" style="display:block;padding:16px 18px;border:1px solid #ffffff;border-radius:3px;font:15px/21px Arial,sans-serif;font-weight:bold;color:#273554;text-decoration:none">{e(label)} &nbsp; ↗</a></td></tr></table><!--<![endif]-->
</td></tr></table>'''
    if x['id']=='E24': images[i]='ajustement'
    alts['ajustement']='Préciser une annonce : remplacer Repensez votre intérieur par Vous envisagez la rénovation complète de votre appartement ?'
    asset=images[i];ext='png' if asset in arts else 'jpg'
    # Chaque visuel accompagne le passage qui introduit sa fonction ou sa scène.
    positions=[2,1,5,4,3,4,3,4,3,4,3,3,3,3,3,3,4,4,4,3,3,3,5,2,2,3,1,4,2,4,2,3]
    insertion=min(positions[i]+(1 if x["id"] in ['E02', 'E03', 'E04', 'E05', 'E06', 'E07', 'E08', 'E09', 'E10', 'E11', 'E12', 'E13', 'E14', 'E15', 'E16', 'E17', 'E18', 'E19', 'E20', 'E21', 'E22', 'E23', 'E25', 'E26', 'E27', 'E28', 'E29', 'E30', 'E31', 'E32'] else 0),len(parts)-1)
    if x['id']=='E24': insertion=4
    body=''
    for j,t in enumerate(parts):
        paragraph='<p style="margin:0 0 20px;font:16px/27px Arial,sans-serif;color:#344158">'+e(t)+'</p>'
        body+=paragraph
        if j==insertion:
            image_file=asset+'.'+ext if asset in arts else asset+'-bandeau.jpg'
            width=550
            body+=f'''<table role="presentation" width="100%"><tr><td style="padding:0 0 20px" align="left"><img src="{{{{assets_url}}}}/{image_file}" width="{width}" alt="{e(alts[asset])}" style="display:block;width:100%;max-width:{width}px;height:auto;border-radius:3px"></td></tr></table>'''
    content=f'''<!doctype html><html lang="fr" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title>{e(x['objet'])}</title><!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml><![endif]--><style>{css}</style></head><body>
<div style="display:none;font-size:1px;line-height:1px;color:#f4f5f7;max-height:0;max-width:0;opacity:0;overflow:hidden;mso-hide:all">{e(x['apercu'])}</div>
<table role="presentation" width="100%" bgcolor="#f4f5f7"><tr><td class="outer" align="center" style="padding:30px 12px">
<!--[if mso]><table role="presentation" width="640"><tr><td><![endif]-->
<table role="presentation" class="card" width="100%" bgcolor="#ffffff" style="max-width:640px;background:#ffffff;border:1px solid #e3e7ed">
<tr><td class="pad" style="padding:35px 44px 27px"><table role="presentation" width="100%"><tr><td><img class="logo" src="{{{{assets_url}}}}/logo-essort.png" width="158" alt="ESSORT" style="display:block;width:158px;height:auto;color:#273554;font:28px Georgia,serif"></td><td align="right" class="kicker" style="font:10px/17px Arial,sans-serif;letter-spacing:1.5px;color:#657188">LA LETTRE<br>DU CABINET</td></tr></table></td></tr>
<tr><td class="pad" style="padding:0 44px"><table role="presentation" width="100%"><tr><td style="border-top:1px solid #dce2eb;padding-top:28px"><p style="margin:0 0 14px;font:10px/16px Arial,sans-serif;letter-spacing:1.4px;color:#657188">ARCHITECTES &amp; ARCHITECTES D’INTÉRIEUR</p><h1 class="headline" style="margin:0 0 25px;font:36px/41px Arial,sans-serif;font-weight:700;letter-spacing:-1.2px;color:#18253e">{e(x['objet'])}</h1></td></tr></table></td></tr>

<tr><td class="pad" style="padding:0 44px 7px">{body}</td></tr>
<tr><td class="pad" style="padding:3px 44px 32px">{action}</td></tr>
<tr><td class="pad" style="padding:0 44px 32px"><p style="margin:0;font:15px/25px Arial,sans-serif;color:#344158">À bientôt,</p><p style="margin:5px 0 0;font:19px/25px Georgia,serif;color:#273554">Loys et Enzo</p><p style="margin:3px 0 0;font:10px/17px Arial,sans-serif;letter-spacing:1.5px;color:#657188">ESSORT</p></td></tr>
</table>
<table role="presentation" width="100%" style="max-width:640px"><tr><td class="pad" align="center" style="padding:24px 38px;font:11px/18px Arial,sans-serif;color:#68748a">Vous recevez cette lettre à la suite de votre demande du guide Essort.<br>{{{{identite_expediteur}}}}<br><a href="{{{{lien_desinscription}}}}" style="color:#68748a;text-decoration:underline">Se désinscrire</a></td></tr></table>
<!--[if mso]></td></tr></table><![endif]--></td></tr></table></body></html>'''
    (P/'html'/f"{x['id']}.html").write_text(content,encoding='utf-8')
    preview=content.replace('{{assets_url}}','../visuels').replace('{{identite_expediteur}}','Aperçu de travail · aucun envoi activé').replace('href="{{lien_desinscription}}"','href="#" onclick="return false" aria-disabled="true"').replace('>Se désinscrire<','>Désinscription à raccorder avant envoi<')
    (P/'apercus-html'/f"{x['id']}.html").write_text(preview,encoding='utf-8')
    plain=re.sub(r'\[([^\]]+)\]\(([^)]+)\)',r'\1 : \2',x['corps'])+'\n\nLoys et Enzo — Essort\n\n{{identite_expediteur}}\nSe désinscrire : {{lien_desinscription}}\n'
    (P/'texte'/f"{x['id']}.txt").write_text(plain,encoding='utf-8')
    manifest.append({'id':x['id'],'jour':x['jour'],'objet':x['objet'],'apercu':x['apercu'],'html':'html/'+x['id']+'.html','texte':'texte/'+x['id']+'.txt','image':image_file,'cta':x['cta']})
(P/'manifest-templates.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2),encoding='utf-8')
# L’aperçu affiche exactement le template exporté (images locales et footer de relecture).
nav=''.join(f'<button class="navitem" data-index="{i}" onclick="selectMail({i})"><span>{x["id"]} · J{x["jour"]} · {x["cta"]}</span>{e(x["objet"])}</button>' for i,x in enumerate(M))
opts=''.join(f'<option value="{i}">{x["id"]} · {e(x["objet"])}</option>' for i,x in enumerate(M))
page='''<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Les lettres Essort — aperçu HTML</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f5f7;color:#273554;font:14px Arial,sans-serif}.shell{display:grid;grid-template-columns:290px 1fr}aside{height:100vh;position:sticky;top:0;background:white;border-right:1px solid #e1e5eb;display:flex;flex-direction:column}.brand{padding:28px 24px;border-bottom:1px solid #e1e5eb}.brand img{width:145px}.brand h2{font-size:16px;margin:24px 0 8px}.brand p{font-size:12px;color:#69758a;line-height:1.7}.badge{font-size:10px;letter-spacing:1px}nav{overflow:auto;padding:12px}.navitem{display:block;width:100%;border:0;text-align:left;background:white;color:#273554;padding:13px;border-radius:8px;margin-bottom:3px;cursor:pointer;font:13px/1.45 Arial}.navitem span{display:block;font-size:9px;letter-spacing:.5px;color:#748198;margin-bottom:4px}.navitem[aria-current=true]{background:#273554;color:white}.navitem[aria-current=true] span{color:#ccd5e4}main{min-width:0;padding:24px 24px 40px}.toolbar,.envelope,.note{max-width:664px;margin:0 auto}.toolbar{display:flex;align-items:center;gap:10px;justify-content:space-between;margin-bottom:18px}.toolbar button,.toolbar a{padding:10px 12px;background:white;border:1px solid #dbe1e9;border-radius:7px;color:#273554;text-decoration:none;font-size:12px;cursor:pointer}.toolbar button:disabled{opacity:.4}.envelope{padding:18px 22px;background:white;border:1px solid #dbe1e9;border-radius:10px;margin-bottom:12px;font-size:13px;line-height:1.6}.envelope small{color:#758198}iframe{display:block;width:100%;max-width:664px;margin:auto;border:0;height:1600px}.note{padding-top:18px;font-size:12px;line-height:1.7;color:#758198}.mobile-picker{display:none}.mode{display:flex;gap:5px}.mode button.active{background:#273554;color:white}a:focus-visible,button:focus-visible{outline:2px solid #537bc1;outline-offset:2px}@media(max-width:800px){.shell{display:block}aside{height:auto;position:static}.brand{padding:18px 22px;display:flex;align-items:center;justify-content:space-between}.brand img{width:125px}.brand h2,.brand p,nav,.badge{display:none}.mobile-picker{display:block;margin:14px 20px;width:calc(100% - 40px);padding:12px;background:white;border:1px solid #dbe1e9;color:#273554}main{padding:12px 0 30px}.toolbar{padding:0 12px;flex-wrap:wrap}.envelope{margin:0 12px 12px}.mode{display:none}.note{padding:18px}.toolbar button,.toolbar a{padding:10px}iframe{max-width:100%!important}}
</style><div class="shell"><aside><div class="brand"><img src="visuels/logo-essort.png" alt="Essort"><h2>La lettre du cabinet</h2><p>32 emails · 12 mois<br>Templates HTML · direction artistique Essort</p><span class="badge">APERÇU · AUCUN ENVOI ACTIVÉ</span></div><select class="mobile-picker" aria-label="Choisir un email" onchange="selectMail(+this.value)">OPTIONS</select><nav aria-label="Les emails">NAV</nav></aside><main><div class="toolbar"><button id="prev" onclick="selectMail(current-1)">←</button><span id="counter"></span><button id="next" onclick="selectMail(current+1)">→</button><div class="mode"><button id="desktop" class="active" onclick="setWidth(664)">Ordinateur</button><button id="mobile" onclick="setWidth(390)">Mobile</button></div><a id="download" download>Télécharger le HTML</a></div><div class="envelope"><small>DE</small> &nbsp; Loys et Enzo — Essort<br><small>OBJET</small> &nbsp; <b id="subject"></b><br><small id="preheader"></small></div><iframe id="email-frame" title="Aperçu du mail Essort" onload="if(typeof fit==='function')fit()"></iframe><p class="note">Les images sont intégrées dans l’aperçu. Les fichiers HTML contiennent les champs d’hébergement, d’expéditeur et de désinscription à raccorder à l’outil d’envoi. Chaque email propose un bouton vers le guide, la méthode Essort ou la réservation d’un échange.<br><a href="sequence-12-mois.md">Tous les textes</a> · <a href="README-templates.md">Utiliser les templates</a></p></main></div><script>
const mails=DATA;let current=0;const f=document.getElementById('email-frame');function fit(){if(f.contentDocument){f.style.height='1px';f.style.height=(f.contentDocument.documentElement.scrollHeight+4)+'px'}}function selectMail(n){if(n<0||n>=mails.length)return;current=n;const x=mails[n];document.querySelectorAll('.navitem').forEach((el,i)=>el.setAttribute('aria-current',String(i===n)));document.querySelector('.mobile-picker').value=n;document.getElementById('counter').textContent=x.id+' · J'+x.jour;document.getElementById('prev').disabled=n===0;document.getElementById('next').disabled=n===31;document.getElementById('subject').textContent=x.objet;document.getElementById('preheader').textContent=x.apercu;document.getElementById('download').href='html/'+x.id+'.html';f.src='apercus-html/'+x.id+'.html';history.replaceState(null,'','#'+x.id);window.scrollTo(0,0)}function setWidth(w){f.style.maxWidth=w+'px';document.getElementById('desktop').classList.toggle('active',w===664);document.getElementById('mobile').classList.toggle('active',w===390);setTimeout(fit,100)}window.addEventListener('resize',()=>setTimeout(fit,100));window.addEventListener('hashchange',()=>{const k=Number(location.hash.replace('#E',''))-1;if(k>=0&&k<32&&k!==current)selectMail(k)});let n=Number(location.hash.replace('#E',''))-1;selectMail(n>=0&&n<32?n:0);
</script></html>'''
page=page.replace('</html>','<script src="personnalisation.js"></script><script src="apercu-personnalisation.js"></script></html>')
page=page.replace('OPTIONS',opts).replace('NAV',nav).replace('DATA',json.dumps(manifest,ensure_ascii=False))
(P/'apercu-sequence.html').write_text(page,encoding='utf-8')
print('32 templates HTML, 32 versions texte, aperçu et manifeste générés.')
